RpgStoryTellersAid/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RpgStoryTellersAid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^stories/', include('stories.urls')),
  url(r'^accounts/', include('accounts.urls')),  
  url(r'^admin/', include(admin.site.urls)),    
)

stories/urls.py
from django.conf.urls import patterns, url

from stories.views import *

urlpatterns = patterns('',
  url(r'^$',                                       StoryList.as_view(),      name='story-list'),
	url(r'^create$',                                 StoryCreate.as_view(),    name='story-create'), 	
	url(r"""^(?P<pk>\d+)/edit$""",                   StoryEdit.as_view(),      name='story-edit'),
	url(r"""^(?P<pk>\d+)/delete$""",                 StoryDelete.as_view(),    name='story-delete'),
	url(r"""^(?P<pk>\d+)$""",                        StoryDetail.as_view(),    name='story-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/create$""",   ChapterCreate.as_view(),  name='chapter-create'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<pk>\d+)/edit$""",    ChapterEdit.as_view(),    name='chapter-edit'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<pk>\d+)$""",         ChapterDetail.as_view(),  name='chapter-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<pk>\d+)/delete$""",  ChapterDelete.as_view(),  name='chapter-delete'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/create$""",                SceneCreate.as_view(),    name='scene-create'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<pk>\d+)/edit$""",      SceneEdit.as_view(),      name='scene-edit'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<pk>\d+)$""",           SceneDetail.as_view(),    name='scene-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<pk>\d+)/delete$""",    SceneDelete.as_view(),    name='scene-delete'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)clues/create$""",                 ClueCreate.as_view(),     name='clue-create'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/clues/(?P<pk>\d+)/edit$""",       ClueEdit.as_view(),       name='clue-edit'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/clues/(?P<pk>\d+)$""",            ClueDetail.as_view(),     name='clue-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/clues/(?P<pk>\d+)/delete$""",     ClueDelete.as_view(),     name='clue-delete'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/castmembers/create$""",           CastMemberCreate.as_view(),     name='castmember-create'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/castmembers/(?P<pk>\d+)/edit$""",   CastMemberEdit.as_view(),       name='castmember-edit'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/castmembers/(?P<pk>\d+)$""",        CastMemberDetail.as_view(),     name='castmember-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/castmembers/(?P<pk>\d+)/delete$""", CastMemberDelete.as_view(),     name='castmember-delete'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/locations/create$""",           LocationCreate.as_view(),     name='location-create'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/locations/(?P<pk>\d+)/edit$""",   LocationEdit.as_view(),       name='location-edit'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/locations/(?P<pk>\d+)$""",        LocationDetail.as_view(),     name='location-detail'),
  url(r"""^(?P<story_pk>\d+)/chapters/(?P<chapter_pk>\d+)/scenes/(?P<scene_pk>\d+)/locations/(?P<pk>\d+)/delete$""", LocationDelete.as_view(),     name='location-delete'),

)

stories/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models

class Story(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	created_by = models.ForeignKey(User)
	
	def get_absolute_url(self):
		return reverse('story-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.name


class Chapter(models.Model):
	number = models.IntegerField()
	title = models.CharField(max_length=200)
	description = models.TextField()
	story = models.ForeignKey('Story')
	
	def get_absolute_url (self):
		return reverse('chapter-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.title

	class Meta:
		ordering = ['number', 'title']


class Scene(models.Model):
	number = models.IntegerField()
	title = models.CharField(max_length=200)
	description = models.TextField()
	chapter = models.ForeignKey('Chapter')
	members = models.ManyToManyField('CastMember', through='SceneCastMember')
	
	def get_absolute_url(self):
		return reverse('scene-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.title

	class Meta:
		ordering = ['number', 'title']

class Clue(models.Model):
	title = models.CharField(max_length=200)
	description = models.TextField()
	scene = models.ForeignKey('Scene')
	
	def get_absolute_url(self):
		return reverse('clue-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.title

	class Meta:
		ordering = ['title', ]

class CastMember(models.Model):
	title = models.CharField(max_length=200)
	description = models.TextField()
	#scene = models.ForeignKey('Scene')
	
	def get_absolute_url(self):
		return reverse('castmember-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.title

	class Meta:
		ordering = ['title', ]
		
class SceneCastMember( models.Model):
	description = models.TextField()
	scene = models.ForeignKey(Scene)
	cast_member = models.ForeignKey(CastMember)


class Location(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	scene = models.ForeignKey('Scene')
	map  = models.FileField(blank=True, upload_to="location_maps")
	
	def get_absolute_url(self):
		return reverse('location-detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name', ]

stories/forms.py
from django.forms import ModelForm
from django.forms.models import modelformset_factory, inlineformset_factory
from stories.models import Scene, SceneCastMember

SceneCastMemberFormset = inlineformset_factory( Scene, SceneCastMember, extra=3, fields=('cast_member', 'description'))

stories/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect

from stories.models import Story, Chapter, Scene, Clue, CastMember, Location
from stories.forms import SceneCastMemberFormset

class StoryList(ListView):
	model = Story
	
	def get_queryset(self):
		return Story.objects.filter(created_by=self.request.user)
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(StoryList, self).dispatch(*args, **kwargs)	


class StoryCreate(CreateView):
	model = Story
	fields = ['name', 'description']

	def form_valid(self, form):
		form.instance.created_by = self.request.user
		return super(StoryCreate, self).form_valid(form)
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(StoryCreate, self).dispatch(*args, **kwargs)


class StoryDetail(DetailView):
	model = Story
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(StoryDetail, self).dispatch(*args, **kwargs)

class StoryEdit(UpdateView):
	model = Story
	fields = ['name', 'description']
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(StoryEdit, self).dispatch(*args, **kwargs)

class StoryDelete(DeleteView):
	model = Story
	success_url = reverse_lazy('story-list')
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(StoryDelete, self).dispatch(*args, **kwargs)
	
class ChapterCreate(CreateView):
	model = Chapter	
	fields = ['number', 'title', 'description']
	
	def get_success_url(self):
		return reverse('story-edit', kwargs={ 'pk' : self.object.story_id})
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ChapterCreate, self).dispatch(*args, **kwargs)
	
	def get_initial(self):
		initial = super(ChapterCreate, self).get_initial()
		story_pk = int(self.kwargs['story_pk'])
		parent_story = Story.objects.get(pk=story_pk)
		initial['number'] = parent_story.chapter_set.count() + 1			
		return initial
	
	def get_context_data(self, **kwargs) :
		context = super(ChapterCreate, self).get_context_data(**kwargs)
		story_pk = int(self.kwargs['story_pk'])
		parent_story = Story.objects.get(pk=story_pk)
		context['story'] = parent_story
		return context

	def form_valid(self, form):
		form.instance.story = self.get_context_data()['story']
		return super(ChapterCreate, self).form_valid(form)
	
	
class ChapterDetail(DetailView):
	model = Chapter
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ChapterDetail, self).dispatch(*args, **kwargs)

			
			
class ChapterEdit(UpdateView):
	model = Chapter
	fields = ['number', 'title', 'description']
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ChapterEdit, self).dispatch(*args, **kwargs)	
	
	def get_success_url(self):
		return reverse('story-edit', kwargs={ 'pk' : self.object.story_id})
	
	def get_context_data(self, **kwargs) :
		context = super(ChapterEdit, self).get_context_data(**kwargs)		
		story_pk = int(self.kwargs['story_pk'])
		parent_story = Story.objects.get(pk=story_pk)
		context['story'] = parent_story
		return context	
		

class ChapterDelete(DeleteView):
	model = Chapter
	success_url = reverse_lazy('story-list')
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ChapterDelete, self).dispatch(*args, **kwargs)
	
	def get_success_url(self):
		return reverse('story-edit', kwargs={ 'pk' : self.object.story_id})
	
	def get_context_data(self, **kwargs) :
		context = super(ChapterDelete, self).get_context_data(**kwargs)
		story_pk = int(self.kwargs['story_pk'])
		parent_story = Story.objects.get(pk=story_pk)
		context['story'] = parent_story
		return context
		
		
class SceneCreate(CreateView):
	model = Scene	
	fields = ['number', 'title', 'description']
	
	def get_success_url(self):
		return reverse('chapter-edit', kwargs={ 'story_pk' : self.object.chapter.story.id,
																							'pk' : self.object.chapter_id})
		
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(SceneCreate, self).dispatch(*args, **kwargs)
	
	def get_initial(self):
		initial = super(SceneCreate, self).get_initial()
		chapter_pk = int(self.kwargs['chapter_pk'])
		parent_chapter = Chapter.objects.get(pk=chapter_pk)
		initial['number'] = parent_chapter.scene_set.count() + 1		
		return initial
	
	def form_valid(self, form):
		form.instance.chapter = self.get_context_data()['chapter']
		return super(SceneCreate, self).form_valid(form)
	
	def get_context_data(self, **kwargs) :
		context = super(SceneCreate, self).get_context_data(**kwargs)		
		chapter_pk = int(self.kwargs['chapter_pk'])
		chapter = Chapter.objects.get(pk=chapter_pk)
		context['chapter'] = chapter
		context['story'] = chapter.story
		return context
		
class SceneDetail(DetailView):
	model = Scene
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(SceneDetail, self).dispatch(*args, **kwargs)
			
class SceneEdit(UpdateView):
	model = Scene
	fields = ['number', 'title', 'description']
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(SceneEdit, self).dispatch(*args, **kwargs)
	
	def get_success_url(self):
		return reverse('chapter-edit', kwargs={ 'story_pk' : self.object.chapter.story.id,
																							'pk' : self.object.chapter_id})

	def get_context_data(self, **kwargs) :
		context = super(SceneEdit, self).get_context_data(**kwargs)		
		chapter_pk = int(self.kwargs['chapter_pk'])
		chapter = Chapter.objects.get(pk=chapter_pk)
		context['chapter'] = chapter
		context['story'] = chapter.story
		return context
	
	def get(self, request, *args, **kwargs):
		scene_pk = int(self.kwargs['pk'])
		self.object = Scene.objects.get(pk=scene_pk)
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		scene_cast_members = self.object.scenecastmember_set.all().values()
		scenecastmember_formset = SceneCastMemberFormset(initial= scene_cast_members, instance=self.object)
		return self.render_to_response(
            self.get_context_data(form=form,
                                  scenecastmember_formset=scenecastmember_formset))

	def post(self, request, *args, **kwargs):		
		self.object = None
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		scenecastmember_formset = SceneCastMemberFormset(request.POST,)
		if (form.is_valid() and scenecastmember_formset.is_valid() ):
			return self.form_valid(form, scenecastmember_formset)
		else:
			return self.form_invalid(form, scenecastmember_formset)
	
	def form_valid(self, form, scenecastmember_formset):        
		self.object = form.save( commit=False)
		self.object.pk = self.kwargs['pk']
		self.object.chapter = self.get_context_data()['chapter'] 
		self.object.save()		
		scenecastmember_formset.instance = self.object
		scenecastmember_formset.save()		
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form, scenecastmember_formset):
		return self.render_to_response(
																	self.get_context_data(form=form,
																											scenecastmember_formset=scenecastmember_formset))

	
	
class SceneDelete(DeleteView):
	model = Scene
	
	def get_success_url(self):
		return reverse('chapter-edit', kwargs={ 'story_pk' : self.object.chapter.story.id,
																							'pk' : self.object.chapter_id})
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(SceneDelete, self).dispatch(*args, **kwargs)
	
	def get_context_data(self, **kwargs) :
		context = super(SceneDelete, self).get_context_data(**kwargs)		
		chapter_pk = int(self.kwargs['chapter_pk'])
		chapter = Chapter.objects.get(pk=chapter_pk)
		context['chapter'] = chapter
		context['story'] = chapter.story
		return context
	
class ClueCreate(CreateView):
	model = Clue		
	fields = ['title', 'description']
	
	def get_success_url(self):
		return reverse('scene-edit', kwargs={ 'story_pk' : self.object.scene.chapter.story.id,
																					'chapter_pk' : self.object.scene.chapter.story.id,
																					'pk' : self.object.scene_id})
		
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ClueCreate, self).dispatch(*args, **kwargs)
		
	def form_valid(self, form):
		form.instance.scene = form.initial['scene']
		return super(ClueCreate, self).form_valid(form)	

	def get_context_data(self, **kwargs) :
		context = super(ClueCreate, self).get_context_data(**kwargs)		
		scene_pk = int(self.kwargs['scene_pk'])
		scene = Scene.objects.get(pk=scene_pk)
		context['scene'] = scene
		context['chapter'] = scene.chapter
		context['story'] = scene.chapter.story
		return context


class ClueDetail(DetailView):
	model = Clue
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ClueDetail, self).dispatch(*args, **kwargs)

			
class ClueEdit(UpdateView):
	model = Clue
	fields = ['title', 'description']
	
	def get_success_url(self):
		return reverse('scene-edit', kwargs={ 'story_pk' : self.object.scene.chapter.story.id,
																					'chapter_pk' : self.object.scene.chapter.story.id,
																					'pk' : self.object.scene_id})
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):

stories/templates/stories/castmember_confirm_delete.html
{% extends "bread_crumb.html" %} 
{% load bootstrap3 %} 

{% block bread_crumb %}	
	<a href="{% url 'story-list' %}">Stories</a> / <a href="{% url 'story-edit' pk=story.id %}">{{story.name}}</a> / <a href="{% url 'chapter-edit' story_pk=story.id pk=chapter.id %}">Chapter {{chapter.number}}: {{ chapter.title }} </a>
	/ <a href="{% url 'scene-edit' story_pk=story.id chapter_pk=chapter.id pk=scene.id%}">Scene {{scene.number}}: {{ scene.title }} </a> 
{% endblock %} 

{% block bread_crumb_page_header %}Cast Member{% endblock %}

{% block bread_crumb_content %}

<form action="" method="post">
	{% csrf_token %}
	<p>Are you sure you want to delete Cast Member {{ object.title }}?</p>
	<input type="submit" value="Confirm" />
</form>
{% endblock %}

stories/templates/stories/castmember_form.html
{% extends "bread_crumb.html" %} 
{% load bootstrap3 %} 

{% block bread_crumb %}	
	<a href="{% url 'story-list' %}">Stories</a> / <a href="{% url 'story-edit' pk=story.id %}">{{story.name}}</a> / <a href="{% url 'chapter-edit' story_pk=story.id pk=chapter.id %}">Chapter {{chapter.number}}: {{ chapter.title }} </a>
	/ <a href="{% url 'scene-edit' story_pk=story.id chapter_pk=chapter.id pk=scene.id%}">Scene {{scene.number}}: {{ scene.title }} </a> 
{% endblock %} 

{% block bread_crumb_page_header %}Cast Member{% endblock %}

{% block bread_crumb_content %}
   
	<form id="castmember_form" action="" method="post" class="form">
		{% csrf_token %}

		{% bootstrap_form form %}
		
		{% buttons %}
			<button type="submit" class="btn btn-primary">
				{% bootstrap_icon "save" %} Save
			</button>
		{% endbuttons %}				    			    
	</form>
{% endblock %}

stories/templates/stories/chapter_detail.html
{% extends "base.html" %} 
{% block content %} 
<div class="page-header">
<h1>{{object.number}} - {{ object.title }}</h1>
</div>
{{ object.description }}

<br>
<a href="{% url 'story-list' %}">Back to Story List</a>
{% endblock %}

stories/templates/stories/clue_confirm_delete.html
{% extends "bread_crumb.html" %} 
{% load bootstrap3 %} 

{% block bread_crumb %}	
	<a href="{% url 'story-list' %}">Stories</a> / <a href="{% url 'story-edit' pk=story.id %}">{{story.name}}</a> / <a href="{% url 'chapter-edit' story_pk=story.id pk=chapter.id %}">Chapter {{chapter.number}}: {{ chapter.title }} </a>
	/ <a href="{% url 'scene-edit' story_pk=story.id chapter_pk=chapter.id pk=scene.id%}">Scene {{scene.number}}: {{ scene.title }} </a> 
{% endblock %} 

{% block bread_crumb_page_header %}Confirm Deleting a Clue{% endblock %}

{% block bread_crumb_content %}  
<form action="" method="post">
	{% csrf_token %}	
	<p>Are you sure you want to delete Clue {{ object.title }}?</p>
	<input type="submit" value="Confirm" />
</form>
{% endblock %}

stories/templates/stories/clue_detail.html
{% extends "base.html" %} 
{% block content %} 
<div class="page-header">
<h1>{{ object.title }}</h1>
</div>
{{ object.description }}

<br>
<a href="{% url 'story-list' %}">Back to Story List</a>
{% endblock %}

stories/templates/stories/scene_form.html
{% extends "bread_crumb.html" %} 
{% load bootstrap3 %} 

{% block bread_crumb %}
	<a href="{% url 'story-list' %}">Stories</a> / <a href="{% url 'story-edit' pk=story.id %}">{{story.name}}</a> / <a href="{% url 'chapter-edit' story_pk=story.id pk=chapter.id %}">Chapter {{chapter.number}}: {{ chapter.title }} </a>
{% endblock %} 

{% block bread_crumb_page_header %}Scene{% endblock %}

{% block bread_crumb_content %} 
	<form id="scene_form" action="" method="post" class="form">
		{% csrf_token %}
		
		{% bootstrap_form form %}

		{% if form.instance.id %}		
		<ul class="nav nav-tabs">
  		<li class="active"><a href="#clues" data-toggle="tab">Clues</a></li>
  		<li><a href="#castmembers" data-toggle="tab">Cast Members</a></li>
  		<li><a href="#locations" data-toggle="tab">Locations</a></li>
		</ul>

		<div class="tab-content">
  		<div class="tab-pane active" id="clues">
  			{% buttons %}  			
					<a id="add-clue-button" class="btn btn-primary" href="{% url 'clue-create'  story_pk=story.id chapter_pk=chapter.id scene_pk=form.instance.id %}">{% bootstrap_icon "plus" %} Add</a>
				{% endbuttons %}
		
				<table id="clue-table" class='table table-striped'>
					<thead>
						<tr>
							<th>Title</th>
							<th>Description</th>
						</tr>
					</thead>
					{% for clue in form.instance.clue_set.all %}    						    		
						<tr>											                    						
							<td width="20%">{{clue.title}}</td>
							<td width="70%">{{clue.description}}</td>
							<td width="10%"><a href="{% url 'clue-edit' story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id pk=clue.pk %}" class="btn btn-default  btn-xs">{%bootstrap_icon "pencil"%} Edit</a>
							<a href="{% url 'clue-delete' story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id pk=clue.pk %}" class="btn btn-default  btn-xs">{%bootstrap_icon "remove-circle"%} Delete</a></td>
						</tr>    			
					{% endfor %}    	
				</table>
			</div>
			<div class="tab-pane" id="castmembers">
				{% buttons %}  			
					<a id="add-castmember-button" class="btn btn-primary" href="{% url 'castmember-create' story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id %}">{% bootstrap_icon "plus" %} Add</a>
				{% endbuttons %}
				{{ scenecastmember_formset.management_form }}
        {{ scenecastmember_formset.non_form_errors }}													
				<table id="castmember-table" class='table table-striped'>
					{% for form in scenecastmember_formset.forms %}
  					{% if forloop.first %}
  						<thead>
  							<tr>
    							{% for field in form.visible_fields %}
    								<th>{{ field.label|capfirst }}</th>
    							{% endfor %}
  							</tr>
  						</thead>
  					{% endif %}
  					<tr >
  						{% for field in form.visible_fields %}
    						<td>    		
    							{% if forloop.first %}
      							{% for hidden in form.hidden_fields %}
      								{{ hidden }}
      							{% endfor %}
    							{% endif %}
      						{{ field.errors.as_ul }}
      						{{ field }}
    						</td>
  						{% endfor %}
  					</tr>
					{% endfor %}	
				</table>
			</div>	
			<div class="tab-pane" id="locations">
  			{% buttons %}  			
					<a id="add-location-button" class="btn btn-primary" href="{% url 'location-create'  story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id %}">{% bootstrap_icon "plus" %} Add</a>
				{% endbuttons %}
		
				<table id="location-table" class='table table-striped'>
					<thead>
						<tr>
							<th>Name</th>
							<th>Description</th>
						</tr>
					</thead>
					{% for location in form.instance.location_set.all %}    						    		
						<tr>											                    						
							<td width="20%">{{location.name}}</td>
							<td width="70%">{{location.description}}</td>
							<td width="10%"><a href="{% url 'location-edit' story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id pk=location.pk %}" class="btn btn-default  btn-xs">{%bootstrap_icon "pencil"%} Edit</a>
							<a href="{% url 'location-delete' story_pk=form.instance.chapter.story.id chapter_pk=form.instance.chapter.id scene_pk=form.instance.id pk=location.pk %}" class="btn btn-default  btn-xs">{%bootstrap_icon "remove-circle"%} Delete</a></td>
						</tr>    			
					{% endfor %}    	
				</table>
			</div>
  	</div>
		{% endif %}
		{% buttons %}
			<button type="submit" class="btn btn-primary">
				{% bootstrap_icon "save" %} Save
			</button>
		{% endbuttons %}				    			    
	</form>
{% endblock %}

stories/templates/stories/story_detail.html
{% extends "base.html" %} 
{% block content %} 
<h1>{{ object.name }}</h1>
{{ object.description }}
{% for chapter in object.chapter_set.all %}
<h2>Chapter {{chapter.number}} - {{chapter.title}}</h2>
	{{chapter.description}}
	{% for scene in chapter.scene_set.all %}
		<h3>{{scene.title}}</h3>
		{{scene.description}}
		<h4>Clues</h4>
		{% for clue in scene.clue_set.all %}
			<h5>{{clue.title}}</h5>
			{{clue.description}}
		{% endfor %}
		<h4>Cast Members</h4>
		{% for cast in scene.castmember_set.all %}
			<h5>{{cast.title}}</h5>
			{{cast.description}}
		{% endfor %}
	{% endfor %}
{% endfor %}
<br>
<a href="{% url 'story-list' %}">Back to Story List</a>
{% endblock %}